version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_rag_project
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./storage:/qdrant/storage
    restart: unless-stopped
